# Generated by Django 2.1 on 2021-02-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='name',
            new_name='uname',
        ),
    ]
